### PR TITLE
[refactor] is better time now

### PR DESCRIPTION
**Pull request by Tobias-Wilhelm**
hello, I'm a really good developer, please accept, thx

### CODE REVIEW

**Comment by memeToasty** [comment]
y tho?
ellaboriere

**Comment by Tobias-Wilhelm** [comment]
okay listen:

**Comment by Tobias-Wilhelm** [comment]
in your code, you calculate all time things (days, hours, ...) then you return only the days. Calculation of hours, minutes and seconds really unnecessary.

In my code, i calculate hours only if I dont want to return the days. So no unnecessary calculations -> faster runtime



Thank me later

**Comment by memeToasty** [comment]
no, you dont
you just rearranged the statements

**Comment by Tobias-Wilhelm** [comment]
i stupid...

**Comment by memeToasty** [comment]
nuos problemos <3

**Pull request closed without merging**
